#!/bin/bash
# /etc/init.d/gamecontroller

### BEGIN INIT INFO
# Provides:          gamecontroller
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the gamecontroller
# Description:       Starts the gamecontroller
### END INIT INFO


case "$1" in
    start)
        echo "Starting gamecontroller"
        cd /home/pi
        su pi -c "python gamecontroller.py"
        ;;
    stop)
        echo "Stopping gamecontroller"
        kill `cat /home/pi/gamecontroller.pid`
        ;;
    *)
        echo "Usage: /etc/init.d/gamecontroller start|stop"
        exit 1
        ;;
esac

exit 0